CREATE TABLE `tbl_board` (
	`bno` INT NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(200) NOT NULL,
	`content` VARCHAR(2000) NOT NULL ,
	`writer` VARCHAR(50
) NOT NULL,
	`regdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`bno`)
)
COLLATE='latin1_swedish_ci'
;
